name: Makefile CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
    - run: npm install

    - name: Setup project
      run: make setup

    - name: Run tests
      run: make test

    - name: Run linter
      run: make lint
